export const FETCH_DIALOGS_REQUEST = "FETCH_DIALOGS_REQUEST";

export const FETCH_DIALOGS_SUCCESS = "FETCH_DIALOGS_SUCCESS";

export const FETCH_DIALOGS_FAILURE = "FETCH_DIALOGS_FAILURE";

export const SET_DIALOGS_GET_START = "SET_DIALOGS_GET_START";

export const SET_DIALOGS_ACTIVE = "SET_DIALOGS_ACTIVE";

export const SET_DIALOGS_SAVED = "SET_DIALOGS_SAVED";

export const SET_DIALOGS_COMPLECTED = "SET_DIALOGS_COMPLECTED";

export const SET_DIALOG_IN_ACTIVE = "SET_DIALOG_IN_ACTIVE";
