export const FETCH_FORGOTPASSWORD_REQUEST = 'FETCH_FORGOTPASSWORD_REQUEST'
export const FETCH_FORGOTPASSWORD_SUCCESS = 'FETCH_FORGOTPASSWORD_SUCCESS'
export const FETCH_FORGOTPASSWORD_FAILURE = 'FETCH_FORGOTPASSWORD_FAILURE'