export const FETCH_EMAIL_REQUEST = 'FETCH_EMAIL_REQUEST'
export const FETCH_EMAIL_SUCCESS = 'FETCH_EMAIL_SUCCESS'
export const FETCH_EMAIL_FAILURE = 'FETCH_EMAIL_FAILURE'

export const FETCH_GOOGLE_REQUEST = 'FETCH_GOOGLE_REQUEST'
export const FETCH_GOOGLE_SUCCESS = 'FETCH_GOOGLE_SUCCESS'
export const FETCH_GOOGLE_FAILURE = 'FETCH_GOOGLE_FAILURE'

export const FETCH_GITHUB_REQUEST = 'FETCH_GITHUB_REQUEST'
export const FETCH_GITHUB_SUCCESS = 'FETCH_GITHUB_SUCCESS'
export const FETCH_GITHUB_FAILURE = 'FETCH_GITHUB_FAILURE'
