export const FETCH_UPDATEPASSWORD_REQUEST = 'FETCH_UPDATEPASSWORD_REQUEST'
export const FETCH_UPDATEPASSWORD_SUCCESS = 'FETCH_UPDATEPASSWORD_SUCCESS'
export const FETCH_UPDATEPASSWORD_FAILURE = 'FETCH_UPDATEPASSWORD_FAILURE'